const actionTypes = {
  ROUTE: "ROUTE",
  SHOW_TOAST: 'SHOW_TOAST',
  REMOVE_TOAST: 'REMOVE_TOAST',
  SUBMIT_SEARCH: 'SUBMIT_SEARCH',
  MEETINGS_FETCHING: "MEETINGS_FETCHING",
  MEETINGS_FETCHED: "MEETINGS_FETCHED",
  MEETING_ADD_FETCHING: "MEETING_ADD_FETCHING",
  MEETING_ADD_FETCHED: "MEETING_ADD_FETCHED"
}

export default actionTypes